# Generated by Django 3.1.7 on 2021-03-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='address',
            field=models.ForeignKey(help_text='Endereço', on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='app.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em'),
        ),
    ]
