# Generated by Django 3.1.7 on 2021-03-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210325_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='address',
            field=models.ForeignKey(help_text='Endereço', on_delete=django.db.models.deletion.CASCADE, related_name='establishment', to='app.address', verbose_name='Endereço'),
        ),
    ]
