# Generated by Django 3.1.7 on 2021-03-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210325_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='service',
            field=models.ManyToManyField(related_name='services', to='app.Service', verbose_name='Serviço(s)'),
        ),
    ]
