# Generated by Django 3.1.7 on 2021-04-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210329_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='service',
            field=models.ManyToManyField(to='app.Service', verbose_name='Serviço'),
        ),
    ]
